---
name: basicvsr_backward
pure_name: basicvsr_backward

gops: [114.27, 457.07]
shapes:
  - [[1, 3, 144, 176], [1, 64, 144, 176]]
  - [[4, 3, 144, 176], [4, 64, 144, 176]]

model: $(home)/basicvsr_backward.pt

cali_input_key: cali_basicvsr_residual_176

time_rountds: 50
time: true
precision: true

mlir_transform: model_transform.py
  --model_name $(name)
  --model_def $(model)
  --test_input $(root)/dataset/basicvsr/$(cali_input_key)/1.npz
  --input_shapes [$(shape_param)]
  --test_result $(workdir)/$(pure_name)_top_outputs.npz
  --mlir $(workdir)/$(pure_name).mlir

mlir_calibration: run_calibration.py $(workdir)/$(pure_name).mlir
  --dataset $(root)/dataset/basicvsr/$(cali_input_key)
  --input_num 10
  -o $(workdir)/$(pure_name)_cali_table

BM1684:
  deploy:
    - model_deploy.py
      --mlir $(workdir)/$(pure_name).mlir
      --quantize F32
      --chip $(target)
      --test_input $(workdir)/$(pure_name)_in_f32.npz
      --test_reference $(workdir)/$(pure_name)_top_outputs.npz
      --model $(workdir)/$(pure_name)_$(target)_f32.bmodel

    - model_deploy.py
      --mlir $(workdir)/$(pure_name).mlir
      --quantize INT8
      --chip $(target)
      --tolerance 0.85,0.45
      --calibration_table $(workdir)/$(pure_name)_cali_table
      --test_input $(workdir)/$(pure_name)_in_f32.npz
      --test_reference $(workdir)/$(pure_name)_top_outputs.npz
      --model $(workdir)/$(pure_name)_$(target)_int8_sym.bmodel
