---

name: resnet101-v1-7
gops: 15.214048232

runtime_cmp: false

model: $(home)/resnet101-v1-7.onnx
batch_sizes: [1, 2, 4, 8]

BM1684X:
  fp_loops:
    - build_env:
        - BMCOMPILER_GROUP_SEARCH_COUNT=1
      opt: "1"
      dyn: "False"
      fp_outdir_template: "static.opt1.fp32.{}b.compilation"
      prec: FP32
    - build_env:
        - BMCOMPILER_GROUP_SEARCH_COUNT=1
      opt: "1"
      dyn: "False"
      fp_outdir_template: "static.opt1.fp16.{}b.compilation"
      prec: FP16
  int8_loops:
    - build_env:
        - BMCOMPILER_GROUP_SEARCH_COUNT=1
      opt: "1"
      dyn: "False"
      int8_outdir_template: "static.opt1.int8.{}b.compilation"

  fp_batch_sizes: $(batch_sizes)

  fp_compile_options:
    python3 -m bmneto
    --model $(model)
    --net_name $(name)
    --shapes [1,3,224,224]
    --target $(target)
    --enable_profile True
